#!/bin/bash

rm /dnnwebportal/src/app/resource/ftp.json

echo {"\"host\"":\"$1\", "\"port\"":\"$2\"} > ./src/app/resource/ftp.json

cat /dnnwebportal/src/app/resource/ftp.json

cd /dnnwebportal

npm run app

rm -r /var/www/html/DNN

cp -r build/ /var/www/html/DNN